[tool.black]
line-length = 100
target-version = ["py311"]
include = ".*\\.py"
exclude = "^/(__pycache__|.venv|build|dist)/"

[tool.ruff]
line-length = 100
src = ["app", "tests"]
extend-exclude = ["__pycache__"]

[tool.ruff.lint]
select = ["E", "F", "W", "I"]
ignore = ["E203", "E501"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"
